### PR TITLE
Determine if a field is async or not by the presence of ato_representation.

### PR DESCRIPTION
**Pull request by tbeadle**
Don't hard-code the list of DRF_FIELDS--this was missing things like SerializerMethodField, ManyRelatedField, and ReadOnlyField.

### CODE REVIEW

**Comment by Vonfry** [comment]
I meet the same issue with `ManyRelatedField` recently.

**Comment by Vonfry** [comment]
We cannot use sync version for `ManyRelatedField` simply like this pr, because the internal methods call some db actions with sync version, which is not allowed.

**Comment by em1208** [comment]
I'm OK to merge this PR to avoid the hardcoding of the fields but there are no tests for all the fields in DRF at the moment so I expect some minor issues which I will look into when I have time. I already merged @Vonfry PR [48](https://github.com/em1208/adrf/pull/48) to fix the issue with the many to many field. Thanks again to both!

**Review by em1208 — APPROVED** [review]
LGTM

**Pull request merged**
