### PR TITLE
Async support for the `ViewSet` class

### PR DESCRIPTION
**Pull request by kartava**
**This PR makes the following changes:**
* Fixes issue: #5

### CODE REVIEW

**Comment by kartava** [comment]
Hi @em1208, this PR is ready for review.

**Comment by em1208** [comment]
Hi @kartava, thanks a lot for your work on this. I will review your PR asap and once merged we I will release a new version of the adrf package.

**Comment by kartava** [comment]
I've bumped `isort` version to `5.12.0` due to these issues:
- # https://github.com/PyCQA/isort/issues/2077
- # https://github.com/PyCQA/isort/pull/2078

**Comment by em1208** [comment]
LGTM

**Comment by Archmonger** [comment]
In the future I recommend squash merging to not clutter the commit history

**Pull request merged**
